baseURL = 'https://tdpie.tech/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '鏅轰簬鍗氬'
theme = 'PaperMod'

[params]
  author = '鍗氫富'
  description = '鍗婂浣撴妧鏈崥瀹紝IT鎶€鏈崥瀹?
  defaultTheme = 'light'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  comments = true

  [params.homeInfoParams]
    Title = ''
    Content = ''

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/TZN-maker'

[[menus.main]]
  identifier = 'home'
  name = '棣栭〉'
  url = '/'
  weight = 10

[[menus.main]]
  identifier = 'notes'
  name = '闅忓績鎵嬭'
  url = '/categories/闅忓績鎵嬭/'
  weight = 20

[[menus.main]]
  identifier = 'semiconductor'
  name = '鍗婂浣撹涓?
  url = '/categories/鍗婂浣撹涓?'
  weight = 30

[[menus.main]]
  identifier = 'it-ai'
  name = 'IT鎶€鏈拰AI'
  url = '/categories/IT鎶€鏈拰AI/'
  weight = 40

[[menus.main]]
  identifier = 'about'
  name = '鍏充簬鎴?
  url = '/about/'
  weight = 50

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[taxonomies]
  tag = 'tags'
  category = 'categories'
