baseURL = 'https://tdpie.tech/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '智于博客'
theme = 'PaperMod'

[params]
  author = '博主'
  description = '半导体技术博客，IT技术博客'
  defaultTheme = 'light'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  comments = true

  [params.homeInfoParams]
    Title = ''
    Content = ''

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/TZN-maker'

[[menus.main]]
  identifier = 'home'
  name = '首页'
  url = '/'
  weight = 10

[[menus.main]]
  identifier = 'notes'
  name = '随心手记'
  url = '/categories/随心手记/'
  weight = 20

[[menus.main]]
  identifier = 'semiconductor'
  name = '半导体行业'
  url = '/categories/半导体行业/'
  weight = 30

[[menus.main]]
  identifier = 'it-ai'
  name = 'IT技术和AI'
  url = '/categories/IT技术和AI/'
  weight = 40

[[menus.main]]
  identifier = 'about'
  name = '关于我'
  url = '/about/'
  weight = 50

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[taxonomies]
  tag = 'tags'
  category = 'categories'